-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 16:47:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userID` INT AUTO_INCREMENT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `loginPsswd` VARCHAR(256) NOT NULL,
  `timeCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `salt` VARBINARY(16) NULL,
  PRIMARY KEY (`userID`));


-- -----------------------------------------------------
-- Table `mydb`.`vault`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vault` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vault` (
  `entryID` VARCHAR(45) NOT NULL,
  `user_userID` INT NOT NULL,
  `serviceUsername` VARCHAR(45) NULL,
  `serviceName` VARCHAR(45) NULL,
  `serviceCategory` VARCHAR(45) NULL,
  `serviceTag` VARCHAR(45) NULL,
  `encryptPassword` VARCHAR(256) NULL,
  `nonce` VARCHAR(256) NULL,
  `timeCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`entryID`, `user_userID`),
  INDEX `fk_vault_user_idx` (`user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_vault_user`
    FOREIGN KEY (`user_userID`)
    REFERENCES `mydb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

